services:
  app:
    build: .
    environment:
      - DATABASE=mydb
      - HOST=db
      - PORT=3306
      - USERNAME=my_user
      - PASSWORD=my_user_password
    ports:
      - "80:5094"
    volumes:
      - .:/app

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data: